image: node:8

stages:
    - build
    - test

build_package:
    stage: build
    script:
        - echo 'CI BUILD'
        # install packages first
        - npm run install
        - bash ./scripts/build_rpm.sh
    tags:
        - cm-official-docker-executor
    artifacts:
        name: build-package-$CI_BUILD_REF
        paths:
            - dist
        expire_in: 1 month

test_package:
    stage: test
    script:
        # install jq
        - apt-get update
        - apt-get install -y jq
        # install node modules
        - npm run install
        # npm audit - install includes audit, but perform specific check and fail if needed
        - audit_report=$(npm audit --json)
        - echo $audit_report
        - actions=$(echo $audit_report | jq .actions | jq length)
        - if [ $actions -ne 0 ]; then echo 'ERROR! vulnerabilities exist'; exit 1; fi
        # linter
        - npm run lint
        # unit tests
        - npm run test && npm run report
    artifacts:
        name: ${CI_COMMIT_REF_NAME}_unittests_coverage
        paths:
            - coverage
    tags:
        - cm-official-docker-executor
