image: node:8

stages:
    - build
    - test
    - publish

test_node4:
    stage: test
    image: node:4  
    script:
        - npm install --global npm@5.10.0
        - npm install mocha@5.2.0
        - npm install nyc@14.0.0
        - npm install --no-optional
        - npm run test-only
    tags:
        - docker-executor

test_package:
    stage: test
    script:
        # install jq
        - apt-get update
        - apt-get install -y jq
        # install node modules
        - npm install
        # npm audit - install includes audit, but perform specific check and fail if needed
        - audit_report=$(npm audit --json)
        - echo $audit_report
        - actions=$(echo $audit_report | jq .actions | jq length)
        - if [ $actions -ne 0 ]; then echo 'ERROR! vulnerabilities exist'; exit 1; fi
        # linter
        - npm run lint
        # unit tests
        - npm run test && npm run check && npm run report
    tags:
        - cm-official-docker-executor
    artifacts:
        name: ${CI_COMMIT_REF_NAME}_unittests_coverage
        paths:
            - coverage

build_package:
    image: f5devcentral/containthedocs:rpmbuild
    stage: build
    script:
        - echo 'CI BUILD'
        # install packages: jq
        - apt-get update
        - apt-get install -y jq
        # install node modules
        - npm run install-production
        - bash ./scripts/build_rpm.sh
    tags:
        - cm-official-docker-executor
    artifacts:
        name: f5-cloud-failover-$CI_BUILD_REF
        paths:
            - dist
        expire_in: 1 month

publish_to_artifactory:
    stage: publish
    # for now publish on develop and master as well (instead of just tags)
    only:
        - tags
        - master
        - develop
    tags:
        - cm-official-docker-executor
    script:
        # If the tag contains a '-', then get RPM from the build artifact, otherwise, get it from dist
        # since no '-' in the tag means it's s release and should have been committed to dist.
        - if [[ $CI_COMMIT_TAG == *"-"* ]]; then
        -     RPM_FILE=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        - else
        -     RPM_FILE=$(ls dist/*.rpm)
        - fi
        - RPM_NAME=$(basename $RPM_FILE)
        - >-
            UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ARTIFACTORY_BEARER_TOKEN}" -X PUT --data-binary @${RPM_FILE}
            ${ARTIFACTORY_BASE_URL}/f5-cloud-failover-rpm/${RPM_NAME})
        - echo $UPLOAD_RESULT
        - if [[ "$UPLOAD_RESULT" == *errors* ]]; then echo error during upload; exit 1; fi

# publish docs to internal pages: - this job MUST be named 'pages'
pages:
    stage: publish
    environment:
        name: staging
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}   
    script:
        - PUBLIC_DIR='./public'
        - mkdir -p ${PUBLIC_DIR}
        # place index.html in public dir
        - cp docs/index.html ${PUBLIC_DIR}/index.html
        #### place code coverage docs under: /coverage-docs ####
        - COVERAGE_DOCS=${PUBLIC_DIR}/coverage
        - mkdir -p ${COVERAGE_DOCS}
        - cp -R coverage/* ${COVERAGE_DOCS}
        #### place code contribution docs (mainly for presentation) under: /contribute-docs ####
        - CONTRIBUTE_DOCS=${PUBLIC_DIR}/contribute-docs
        - CONTRIBUTE_DIR=contributing
        # install presentation site dependencies
        - cd ${CONTRIBUTE_DIR} && npm install && cd ..
        - mkdir -p ${CONTRIBUTE_DOCS}
        - cp -R ${CONTRIBUTE_DIR}/* ${CONTRIBUTE_DOCS}
        # make relative links absolute - this could be better...
        # ![diagram](../test/README.md) -> ![diagram](https://base.url/../test/README.md)
        - BASE_URL_FOR_LINKS=${CI_PROJECT_URL}/tree/${CI_COMMIT_REF_NAME}/${CONTRIBUTE_DIR}/
        - README=${CONTRIBUTE_DOCS}/README.md
        # make absolute URL(s) for relative URL(s) outside current directory '../'
        - sed -i -E 's/\[.*\]\(\.\./&SED_TEMP/' ${README} && sed -i "s|..SED_TEMP|${BASE_URL_FOR_LINKS}..|" ${README}
    tags:
        - cm-official-docker-executor
    artifacts:
        paths:
            - public
    only:
        - develop
