image: node:8

stages:
    - build
    - test
    - publish

build_package:
    stage: build
    image: f5devcentral/containthedocs:rpmbuild
    script:
        - echo 'CI BUILD'
        # install jq
        - apt-get update
        - apt-get install -y jq
        # install node modules
        - npm install
        - bash ./scripts/build_rpm.sh
    tags:
        - cm-official-docker-executor
    artifacts:
        name: build-package-$CI_BUILD_REF
        paths:
            - dist
        expire_in: 1 month

test_node4:
    stage: test
    image: node:4  
    script:
        - npm install --global npm@5.10.0
        - npm install mocha@5.2.0
        - npm install nyc@14.0.0
        - npm install --no-optional
        - npm run test-only
    tags:
        - docker-executor

test_package:
    stage: test
    script:
        # install jq
        - apt-get update
        - apt-get install -y jq
        # install node modules
        - npm install
        # npm audit - install includes audit, but perform specific check and fail if needed
        - audit_report=$(npm audit --json)
        - echo $audit_report
        - actions=$(echo $audit_report | jq .actions | jq length)
        - if [ $actions -ne 0 ]; then echo 'ERROR! vulnerabilities exist'; exit 1; fi
        # linter
        - npm run lint
        # unit tests
        - npm run test && npm run report
    tags:
        - cm-official-docker-executor
    artifacts:
        name: ${CI_COMMIT_REF_NAME}_unittests_coverage
        paths:
            - coverage

# publish docs to internal pages: - this job MUST be named 'pages'
pages:
    stage: publish
    environment:
        name: staging
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}   
    script:
        - PUBLIC_DIR='./public'
        - mkdir -p ${PUBLIC_DIR}
        #### place code coverage docs under: /coverage-docs ####
        - COVERAGE_DOCS=${PUBLIC_DIR}/coverage-docs
        - mkdir -p ${COVERAGE_DOCS}
        - cp -R coverage/* ${COVERAGE_DOCS}
    tags:
        - cm-official-docker-executor
    artifacts:
        paths:
            - public
    only:
        - develop
