openapi: '3.0.0'
info:
  version: 0.9.0
  title: Cloud Failover (CF) Extension
  license:
    name: MIT
servers:
  - url: http://192.0.2.1:443/mgmt/shared/cloud-failover
paths:
  /declare:
    get:
      summary: List configuration
      operationId: ops.declare
      tags:
        - Configuration
      responses:
        '200':
          description: Configuration response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Configuration"
              example:
                message: 'success'
                declaration:
                  $ref: "#/components/examples/configurationExample"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Update configuration
      operationId: ops.declare
      tags:
        - Configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Configuration"
            example:
              $ref: "#/components/examples/configurationExample"
      responses:
        '200':
          description: Configuration response
          content:
            application/json:    
              schema:
                $ref: "#/components/examples/configurationExample"
              example:
                message: 'success'
                declaration:
                  $ref: "#/components/examples/configurationExample"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /trigger:
    post:
      summary: Trigger failover
      operationId: ops.trigger
      tags:
        - Trigger
      responses:
        '200':
          description: Configuration response
          content:
            application/json:    
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: success
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Configuration:
      properties:
        class:
          type: string
        environment:
          type: string
        externalStorage:
          type: object
        failoverAddresses:
          type: object
        failoverRoutes:
          type: object 
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
  examples:
    configurationExample:
      class: Cloud_Failover
      environment: azure
      externalStorage:
        scopingTags:
          F5_CLOUD_FAILOVER_LABEL: mydeployment
      failoverAddresses:
        scopingTags:
          F5_CLOUD_FAILOVER_LABEL: mydeployment
      failoverRoutes:
        scopingTags:
          F5_CLOUD_FAILOVER_LABEL: mydeployment
        scopingAddressRanges:
          - '192.168.1.0/24'