openapi: '3.0.0'
info:
  version: 0.9.0
  title: Cloud Failover (CF) Extension
  license:
    name: Apache License 2.0
servers:
  - url: https://192.0.2.1:443/mgmt/shared/cloud-failover
paths:
  /declare:
    get:
      summary: List configuration
      tags:
        - Configuration
      responses:
        '200':
          description: Configuration response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Update configuration
      tags:
        - Configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Configuration"
      responses:
        '200':
          description: Configuration response
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /trigger:
    post:
      summary: Trigger failover
      tags:
        - Trigger
      responses:
        '200':
          description: Configuration response
          content:
            application/json:    
              schema:
                type: object
                properties:
                  message:
                    type: string
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Configuration:
      properties:
        class:
          type: string
        environment:
          type: string
        schemaVersion:
          type: string
        useMetadata:
          type: string
        storageResource:
          type: string
        storageTags:
          type: array
          items:
            type: object
        managedRoutes:
          type: array
          items:
            type: object
        addressTags:
          type: array
          items:
            type: object
    ConfigurationResponse:
      properties:
        message:
          type: string
        declaration:
          type: object
          $ref: "#/components/schemas/Configuration"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth: []