openapi: '3.0.0'
info:
  version: 0.9.0
  title: Cloud Failover (CF) Extension
  description: F5 Cloud Failover (CF) is an iControl LX Extension delivered as a TMOS-independent RPM file. Installing the TS Extension on BIG-IP enables you to declaratively configure BIG-IP devices for automatic failover in cloud environments by POSTing a single JSON declaration to CF’s declarative REST API endpoint.
  license:
    name: Apache License 2.0
servers:
  - url: https://192.0.2.1:443/mgmt/shared/cloud-failover
paths:
  /declare:
    get:
      summary: List configuration
      tags:
        - Configuration
      responses:
        '200':
          description: Configuration Response
          content:
            'application/json; charset=UTF-8':
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Update configuration
      tags:
        - Configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Configuration"
      responses:
        '200':
          description: Configuration response
          content:
            'application/json; charset=UTF-8':
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /trigger:
    post:
      summary: Trigger failover
      tags:
        - Trigger
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  default: 'execute'
      responses:
        '200':
          description: Configuration response
          content:
            'application/json; charset=UTF-8':
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: 'in_progress'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Configuration:
      type: object
      properties:
        class:
          type: string
          default: "Cloud_Failover"
        environment:
          type: string
          enum:
            - azure
            - aws
            - gce
          default: "azure"
        schemaVersion:
          type: string
          default: "0.9.0"
        useMetadata:
          type: string
          default: "true"
        storageResource:
          type: string
          default: "mystorageaccount"
        storageTags:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
                default: "F5_CLOUD_FAILOVER_STORAGE_LABEL"
              value:
                type: string
                default: "mydeployment"
        failoverRoutes:
          type: object
          properties:
            scopingTags:
              type: object
              properties:
                key:
                  type: string
                  default: "F5_CLOUD_FAILOVER_STORAGE_LABEL"
                value:
                  type: string
                  default: "mydeployment"
            scopingAddressRanges:
              type: array
              default: "192.0.2.0/24"
        addressTags:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
                default: "F5_CLOUD_FAILOVER_LABEL"
              value:
                type: string
                default: "mydeployment"
    ConfigurationResponse:
      type: object
      properties:
        message:
          type: string
          default: 'success'
        declaration:
          type: object
          $ref: "#/components/schemas/Configuration"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
