openapi: "3.0.0"
info:
  version: 1.5.0
  title: Cloud Failover (CF) Extension
  description: F5 Cloud Failover (CFE) is an iControl LX Extension delivered as a TMOS-independent RPM file. Installing the CFE Extension on BIG-IP enables you to declaratively configure BIG-IP devices for automatic failover in cloud environments by POSTing a single JSON declaration to CF’s declarative REST API endpoint.
  license:
    name: Apache License 2.0
servers:
  - url: https://192.0.2.1:443/mgmt/shared/cloud-failover
paths:
  /info:
    get:
      summary: List extension information
      tags:
        - Information
      responses:
        "200":
          description: Information Response
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/InformationResponse"
              example:
                version: "1.5.0"
                release: "1"
                schemaCurrent: "1.5.0"
                schemaMinimum: "0.9.1"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /declare:
    get:
      summary: List configuration
      tags:
        - Configuration
      responses:
        "200":
          description: Configuration Response
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Update configuration
      tags:
        - Configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Configuration"
            example:
              class: Cloud_Failover
              environment: azure
              externalStorage:
                scopingTags:
                  f5_cloud_failover_label: mydeployment
              failoverAddresses:
                enabled: true
                scopingTags:
                  f5_cloud_failover_label: mydeployment
              failoverRoutes:
                enabled: true
                scopingTags:
                  f5_cloud_failover_label: mydeployment
                scopingAddressRanges:
                  - range: "192.0.2.0/24"
                defaultNextHopAddresses:
                  discoveryType: static
                  items:
                    - "192.0.2.10"
                    - "192.0.2.11"
              controls:
                class: Controls
                logLevel: info
      responses:
        "200":
          description: Configuration response
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
              example:
                message: success
                declaration:
                  class: Cloud_Failover
                  environment: azure
                  schemaVersion: "0.9.1"
                  externalStorage:
                    scopingTags:
                      f5_cloud_failover_label: mydeployment
                  failoverAddresses:
                    scopingTags:
                      f5_cloud_failover_label: mydeployment
                  failoverRoutes:
                    scopingTags:
                      f5_cloud_failover_label: mydeployment
                    scopingAddressRanges:
                      - range: "192.0.2.0/24"
                    defaultNextHopAddresses:
                      discoveryType: static
                      items:
                        - "192.0.2.10"
                        - "192.0.2.11"
                  controls:
                    class: Controls
                    logLevel: info
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /trigger:
    post:
      summary: Trigger failover
      tags:
        - Trigger
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
            examples:
              execute:
                value:
                  action: execute
              dry-run:
                value:
                  action: dry-run
      responses:
        "200":
          description: Configuration response
          content:
            "application/json; charset=UTF-8":
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TaskStateResponse"
                  - $ref: "#/components/schemas/DryRunResponse"
        "500":
          description: Failover task failed
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/TaskStateResponse"
              example:
                taskState: FAILED
                message: Failover failed because of x
                timestamp: 2019-09-25T22:12:52.137Z
                instance: failover1.local
                failoverOperations:
                  routes: {}
                  addresses: {}
                code: 500
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                  taskState: FAILED
                  message: Failover Unexpected Error
                  code: 500
    get:
      summary: Show triggered failover task status
      tags:
        - Trigger
      responses:
        "202":
          description: Failover task is running
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/TaskStateResponse"
              example:
                  taskState: RUNNING
                  message: Failover running
                  timestamp: 2019-09-25T22:12:52.137Z
                  instance: failover1.local
                  failoverOperations:
                    routes: {}
                    addresses: {}
                  code: 202
        "200":
          description: Successful failover task
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/TaskStateResponse"
              example:
                  taskState: SUCCEEDED
                  message: Failover Completed Successfully
                  timestamp: 2019-09-25T23:44:44.381Z
                  instance: failover0.local
                  failoverOperations:
                    routes: {}
                    addresses: {}
                  code: 200
        "500":
          description: Failed failover task
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/TaskStateResponse"
              example:
                  taskState: FAILED
                  message: Failover failed because of x
                  timestamp: 2019-09-25T22:12:52.137Z
                  instance: failover1.local
                  failoverOperations:
                    routes: {}
                    addresses: {}
                  code: 500
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                  taskState: FAILED
                  message: Failover Unexpected Error
                  code: 500
  /reset:
    post:
      summary: Reset failover state file
      tags:
        - Reset
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resetStateFile:
                  type: boolean
            example:
              resetStateFile: true
      responses:
        "200":
          description: Reset State Response
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ResponseWithMessageString"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /inspect:
    get:
      summary: List associated cloud objects
      tags:
        - Information
      responses:
        "200":
          description: Inspect Response
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/InspectResponse"
              example:
                instance: "123"
                addresses:
                  - privateIpAddress: "1.1.1.1"
                    publicIpAddress: "40.40.40.40"
                    networkInterfaceId: "000AAA"
                routes:
                  - routeTableId: "123"
                    routeTableName: "ABC"
                    networkId: "123"
                hostName: "failover1.local"
                deviceStatus: "active"
                trafficGroup:
                  - name: "/Common/traffic-group-1"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Configuration:
      type: object
      properties:
        class:
          type: string
          default: "Cloud_Failover"
        environment:
          type: string
          enum:
            - azure
            - aws
            - gcp
        schemaVersion:
          type: string
        externalStorage:
          type: object
          properties:
            scopingTags:
              type: object
              additionalProperties: true
        failoverAddresses:
          type: object
          properties:
            scopingTags:
              type: object
              additionalProperties: true
        failoverRoutes:
          type: object
          properties:
            enabled:
              type: string
            routeGroupDefinitions:
              type: array
              properties:
                scopingTags:
                  type: object
                  additionalProperties: true
                scopingAddressRanges:
                  type: array
                  items:
                    type: object
                    properties:
                      range:
                        type: string
                defaultNextHopAddresses:
                  type: object
                  nullable: true
                  properties:
                    discoveryType:
                      type: string
                    items:
                      type: array
                      items:
                        type: string
        controls:
          type: object
          properties:
            class:
              type: string
            logLevel:
              type: string
    InformationResponse:
      type: object
      properties:
        version:
          type: string
        release:
          type: string
        schemaCurrent:
          type: string
        schemaMinimum:
          type: string
    InspectResponse:
      type: object
      properties:
        instance:
          type: string
        addresses:
          type: array
        routes:
          type: array
        hostName:
          type: string
        deviceStatus:
          type: string
          enum:
            - active
            - standby
        trafficGroup:
          type: array
          properties:
            name:
              type: string
    ConfigurationResponse:
      type: object
      properties:
        message:
          type: string
        declaration:
          $ref: "#/components/schemas/Configuration"
    TaskStateResponse:
      type: object
      properties:
        taskState:
          type: string
          enum:
            - "RUNNING"
            - "SUCCEEDED"
            - "FAILED"
        timestamp:
          type: string
        instance:
          type: string
        failoverOperations:
          type: object
          properties:
            routes:
              type: object
            addresses:
              type: object
        code:
          type: string
    DryRunResponse:
      type: object
      properties:
        addresses:
          type: object
        routes:
          type: object
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    ResponseWithMessageString:
      type: object
      properties:
        message:
          type: string
    TriggerStateResponse:
      type: object
      properties:
        message:
          type: object
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
